# Generated by Django 5.1.5 on 2025-02-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginationapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_year',
            new_name='published',
        ),
    ]
