# Generated by Django 5.1.5 on 2025-02-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30)),
                ('marks', models.IntegerField()),
                ('age', models.IntegerField()),
                ('date_admited', models.DateField()),
                ('date_passed', models.DateField()),
            ],
        ),
    ]
