# Generated by Django 5.1.5 on 2025-02-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
