# Generated by Django 5.1.5 on 2025-02-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelinheritanceapp', '0002_bank_b_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('ulocation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='college',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modelinheritanceapp.university',),
        ),
    ]
